services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prisma:
    image: node:22-alpine
    container_name: prisma
    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - ./prisma:/app/prisma
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres

volumes:
  db-data:
