export const enum ENV {
  PORT = 'PORT',
  DATABASE_URL = 'DATABASE_URL',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  COOKIE_SECRET = 'COOKIE_SECRET',
}
